/**
 * build.js
 * -----------------------------------------------------
 * Auto-generates dashboards.html by scanning this folder
 * for .html files and reading small metadata comments
 * from the top of each one.
 *
 * Add these 3 lines near the top of any dashboard file
 * you want listed on the hub page:
 *
 *   <!-- hub:tag Competitive Intel -->
 *   <!-- hub:title Pool Maxx vs. Pool Shark -->
 *   <!-- hub:desc Instagram & Meta ad comparison. -->
 *
 * If a file has no hub: comments, it's skipped from the
 * hub page automatically (so build.js and dashboards.html
 * itself are never listed).
 *
 * Nothing else needs to change in your Cloudflare setup:
 *   Build command:            node build.js
 *   Build output directory:   /
 * -----------------------------------------------------
 */

const fs = require("fs");
const path = require("path");

const ROOT = __dirname;
const OUTPUT_FILE = "dashboards.html";
const SKIP_FILES = new Set([OUTPUT_FILE]);

function readMeta(content) {
  const tag = content.match(/<!--\s*hub:tag\s+(.*?)\s*-->/);
  const title = content.match(/<!--\s*hub:title\s+(.*?)\s*-->/);
  const desc = content.match(/<!--\s*hub:desc\s+(.*?)\s*-->/);
  if (!tag && !title && !desc) return null; // not a hub-listed file
  return {
    tag: tag ? tag[1] : "Dashboard",
    title: title ? title[1] : "Untitled dashboard",
    desc: desc ? desc[1] : "",
  };
}

function escapeHtml(str) {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

function buildCards() {
  const files = fs.readdirSync(ROOT).filter(
    (f) => f.endsWith(".html") && !SKIP_FILES.has(f)
  );

  const cards = [];
  for (const file of files) {
    const content = fs.readFileSync(path.join(ROOT, file), "utf8");
    const meta = readMeta(content);
    if (!meta) continue;
    cards.push(`
    <a class="card" href="${escapeHtml(file)}">
      <span class="tag">${escapeHtml(meta.tag)}</span>
      <h2>${escapeHtml(meta.title)}</h2>
      <p>${escapeHtml(meta.desc)}</p>
      <div class="go">Open dashboard &rarr;</div>
    </a>`);
  }

  if (cards.length === 0) {
    return `
    <p style="color:var(--ink-soft); font-size:14px;">
      No dashboards found yet. Add <code>&lt;!-- hub:title --&gt;</code> comments
      to a .html file to list it here.
    </p>`;
  }

  return cards.join("\n");
}

const TEMPLATE = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Pool Maxx — Dashboards</title>
<style>
  :root{
    --bg:#F4F9F8;
    --card:#FFFFFF;
    --ink:#122B29;
    --ink-soft:#5C7472;
    --line:#DCEAE7;
    --teal:#0E6C63;
    --teal-dark:#0A4D46;
    --aqua:#12A594;
    --aqua-soft:#DDF3EF;
  }
  *{box-sizing:border-box;}
  body{
    margin:0;
    background:var(--bg);
    color:var(--ink);
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
  }
  .wrap{ max-width:1000px; margin:0 auto; padding:44px 28px 60px; }
  header{ margin-bottom:34px; }
  header h1{ margin:0 0 6px; font-size:26px; font-weight:800; letter-spacing:-0.02em; color:var(--teal-dark); }
  header p{ margin:0; font-size:14px; color:var(--ink-soft); }
  .grid{
    display:grid;
    grid-template-columns:repeat(auto-fill, minmax(260px, 1fr));
    gap:18px;
  }
  .card{
    background:var(--card);
    border:1px solid var(--line);
    border-radius:16px;
    padding:22px 22px 20px;
    text-decoration:none;
    color:inherit;
    display:block;
    transition:transform .12s ease, box-shadow .12s ease, border-color .12s ease;
  }
  .card:hover{
    transform:translateY(-2px);
    box-shadow:0 8px 20px rgba(14,108,99,0.08);
    border-color:var(--aqua);
  }
  .card .tag{
    display:inline-block;
    font-size:11px; font-weight:700; text-transform:uppercase; letter-spacing:0.04em;
    background:var(--aqua-soft); color:var(--teal);
    padding:3px 10px; border-radius:999px; margin-bottom:12px;
  }
  .card h2{ margin:0 0 6px; font-size:17px; font-weight:800; }
  .card p{ margin:0; font-size:13px; color:var(--ink-soft); line-height:1.5; }
  .card .go{ margin-top:14px; font-size:12.5px; font-weight:700; color:var(--teal); }
  footer{ margin-top:40px; font-size:12px; color:var(--ink-soft); }
</style>
</head>
<body>
<div class="wrap">
  <header>
    <h1>Pool Maxx — Dashboards</h1>
    <p>All dashboards in one place. Click any card to open it.</p>
  </header>
  <div class="grid">
{{CARDS}}
  </div>
  <footer>This page is auto-generated by build.js — do not edit it by hand, your changes will be overwritten on the next deploy.</footer>
</div>
</body>
</html>
`;

const html = TEMPLATE.replace("{{CARDS}}", buildCards());
fs.writeFileSync(path.join(ROOT, OUTPUT_FILE), html);
console.log(`✔ dashboards.html regenerated.`);
